### ISSUE TITLE
Issues using those examples with a JC4827W543 board. 

### ISSUE THREAD

**Issue by 01GOD** [bitbank2/CYD_Projects#1]
Hi, 

Thanks for posting that and adding some compatibility with JC4827W543 boards, but there are issues. 

I am in the mode of getting a JC4827W543 to do something useful right now, and can beta test updates to those examples this next week also. 

The only example that displayed properly was the soundboard so far. I tried the weather and clock examples, but those stayed blank. 

Sadly the soundboard example loaded and auto-played the first sample without any button having been pressed. I tried pressing various buttons after that, but there was no response. 

Recommendations on how to make that soundboard example function properly? I would like to make a touchscreen synthesizer, so that example seems like at least a starting point. 

Thanks in advance!

**Comment by bitbank2** [comment]
It sounds like you didn't change the DISPLAY_CYD_xxx value for your display. The JC4827W543 is my favorite "CYD" and all sketches work properly on it. Can you show me what your failing sketch looks like?

**Comment by 01GOD** [comment]
Thanks for explaining about DISPLAY_CYD_xxx. I can have a look at that in the code. 

Glad to hear it's the current favorite! (because I have one and also because that makes it seem like it's maybe the best one of those so far)

**Comment by 01GOD** [comment]
The other example sketches I tried (clock and weather) didn't "fail". Ah. The clock example is displaying now, but the buttons aren't functioning. Seems disconnecting and reconnecting it made it reset more fully and now it at least displays and animates. 

Those buttons aren't functioning either though. If it matters, the LVGL that I have installed is 8.3.3 seemingly. 

Would like to at least get that soundboard issue (where it auto-plays first sound and doesn't respond to any cap touch button presses after that) solved. Any advice on solving that?

**Comment by bitbank2** [comment]
LVGL is not used in any of my examples and doesn't have an effect on them. Now it sounds like you're not selecting the right touch sensor type. There are 2 different flavors of JC4827W543 - one has resistive touch and one has capacitive. The resistive touch support is part of my bb_spi_lcd library, but bb_captouch (capacitive touch) is in a different library. You need to provide more details about what you own, what code you're using and what results you get. A simple "it didn't work" is insufficient because of all of the many ways things can go wrong.

**Comment by 01GOD** [comment]
Ah! OK. Had assumed it was for cap touch mainly. It's the cap touch edition, so is there a var necessary to change to set it to cap touch mode? Thanks in advance! 
PS: Changing that #define to DISPLAY_CYD_543 in that weather example made that function. So thanks for recommending having a look at that earlier. 

Trying to get that soundboard functioning properly, as that seems closest to a synthesizer type of app.

**Comment by bitbank2** [comment]
Take a look in the gif_example for how to switch between resistor or capacitive touch. I may not have fully fleshed out capacitive touch info for every board in every sketch. I'm going to close this issue because I think you're on the right path now to get everything working. It's not easy to support every possible board configuration with every sample sketch. The biggest challenge is the cap touch ones because I haven't hard-coded the GPIO info into my libraries (yet).

**Comment by 01GOD** [comment]
In that soundboard example I added another board definition: 
`
#define CYD_543C

#ifdef CYD_543C
// #define TOUCH_CAPACITIVE
#define LCD DISPLAY_CYD_543
#define CAP_TOUCH
#define TOUCH_SDA 8
#define TOUCH_SCL 4
#define TOUCH_INT 3
#define TOUCH_RST 38
#define EXAMPLE_STD_BCLK    GPIO_NUM_42     // I2S bit clock io number
#define EXAMPLE_STD_WS      GPIO_NUM_2      // I2S word select io number
#define EXAMPLE_STD_DOUT    GPIO_NUM_41 
#endif
`
So now it DOES respond to cap touch, but sadly it ONLY plays that 2001 quote and plays it TWICE when the screen is touched ANYWHERE. 

Recommended solution?

**Comment by 01GOD** [comment]
Confirmed that soundboard is calling playSound() twice each touch. And weirdly it calls the second one after playing the sound. And more weirdly, it still called it again after I added `ti.count=0;` below that playSound() call. 

Additionally, the y seems to be mapped to x. And the x seems to be incorrectly measured, as its range isn't from 0 on either side of the display.

**Comment by bitbank2** [comment]
The touch controllers on the other CYDs are 90 degrees rotated from the JC4827xxx. I'll update it to correct that. I only recently got the cap touch version of this board and based most of my examples off of the resistive touch version.

**Comment by 01GOD** [comment]
> The touch controllers on the other CYDs are 90 degrees rotated from the JC4827xxx. I'll update it to correct that. I only recently got the cap touch version of this board and based most of my examples off of the resistive touch version.

Ah, OK! Would be great to have a functional starting point for other projects, so thanks in advance for updating that for the cap touch edition! 

By the way, tried Squareline Studio and LVGL together to make anything on one of those boards? Supposedly that is what the "volos projects" guy on yt switched to mainly.

**Comment by bitbank2** [comment]
LVGL is a long story - I'm adding my imaging codecs and trying to improve the project, but my CYD_Projects will always be simple starting points that are self-contained.

**Comment by 01GOD** [comment]
Ah, alright. It is nice to have an alternative honestly. So thanks again for posting those. Looking forward to that update! 

By the way, was that modification that needs to be done to make that function properly (rotating XY orientation of that cap touch sensor reading) in the bb_captouch library? (In case I want to make it function sooner than the update is launched.)

**Comment by bitbank2** [comment]
Yes, look in the lcd_clock project for bbct.setOrientation()

**Comment by 01GOD** [comment]
Thanks! Actually got it running by setting rotation to 0 in original .ino. Still plays each sample twice, but maybe they are in there twice each.
